### ISSUE TITLE
Location EU API update

### ISSUE THREAD

**Issue by Stiddle** [jubepue/homebridge-petkit-pet-feeder#2]
Hey Jubepue,
thank you very much for your great work. I would be happy to get the plugin working in the Europe, Germany location. I've already read out the http requests. What do you need from me to get the plugin working in the EU? Many greetings

**Comment by jubepue** [comment]
Thanks for your help.
I need a screenshot of the data captured by the charles application. Please visit: https://github.com/jubepue/homebridge-petkit-pet-feeder/wiki/Capture-using-Charles
At point 4 you must go to options and enable or disable the light mode or manual lock of the feeder.
![4CC738B4-3EC2-4E72-A562-01695C8B6CEC](https://user-images.githubusercontent.com/47013466/175830571-97053d8b-47a1-4ccd-9850-4b732cf93a77.jpeg)

Regards
Jubepue

**Comment by jubepue** [comment]
Hi,
there is a new release that solves your request https://github.com/jubepue/homebridge-petkit-pet-feeder/releases/tag/v2.3.0
