### ISSUE TITLE
About petkit fresh element infiniti config

### ISSUE THREAD

**Issue by MarkRushB** [jubepue/homebridge-petkit-pet-feeder#3]
Hi Julio,
I opened this issue for **petkit fresh element infiniti**'s support, below is my charles screenshot, if you need any help, please let me know!
Thanks for your work!
![image](https://user-images.githubusercontent.com/57408875/177013521-aa7c32a1-937e-4d15-a4b8-7039ee3d7d67.png)

**Comment by jubepue** [comment]
Hi,
Please send the screenshot when changing the manual lock or the light mode.
Note the first line "post" and the last line "id="

![4CC738B4-3EC2-4E72-A562-01695C8B6CEC](https://user-images.githubusercontent.com/47013466/175830571-97053d8b-47a1-4ccd-9850-4b732cf93a77.jpeg)

tku
jubepue

**Comment by MarkRushB** [comment]
Hi

**Comment by MarkRushB** [comment]
Hi jubepue,

I refetch the data, please take a look and let me know if you have any other questions!

![批注 2022-07-04 160126](https://user-images.githubusercontent.com/57408875/177212590-c7091144-e916-45ea-a030-b18ae2b89b89.png)

**Comment by jubepue** [comment]
Hi,
A new beta is uploaded, please test it and tell me back.
https://github.com/jubepue/homebridge-petkit-pet-feeder/releases/tag/v2.3.2-beta.1

Regards
jubepue
